version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ferhat
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: invoicify
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: .
    ports: 
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

volumes:
  postgres_data:
