version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ferhat
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: invoicify
    volumes:
      - postgres_data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports: 
      - "3000:3000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - ./shared:/shared
      - /app/node_modules
    command: sh -lc "npm ci && npm run dev"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports: 
      - 5173:80
    depends_on :
     - server

volumes:
  postgres_data:
