
# --- stage 1: install dependenies for slim build
FROM node:20-alpine AS deps

WORKDIR /app
COPY  server/package*.json ./  

RUN npm ci

# --- stage 2: developement runtime
From node:20-alpine
WORKDIR /app 

COPY  --from=deps /app/node_modules ./node_modules

COPY ./server .
COPY shared ./shared
EXPOSE 3000

CMD [ "npm", "run","dev" ]

