name: Tests (server)

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "server/**"
      - ".github/workflows/ci.yml"

#cancel older run on the same branch
concurrency:
  group: server-tests-${{github.ref}}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: server/package-lock.json

      - name: Server lint + typecheck
        working-directory: server
        run: |
          npm ci
          npm run lint
          npm run typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}

      - name: Run tests (CI)
        working-directory: server
        run: |
          npm ci 
          npm run test:ci
      - name: Upload coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-coverage
          path: server/coverage
          if-no-files-found: warn
